# TCL File Generated by Component Editor 23.1
# Mon Apr 28 21:38:36 IDT 2025
# DO NOT MODIFY


# 
# irq_controller "IRQ raise and clear" v1.0
#  2025.04.28.21:38:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module irq_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME irq_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "IRQ raise and clear"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL irq_controller_minimal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file irq_controller.sv SYSTEM_VERILOG PATH irq_controller.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 interrupt end
set_interface_property s0 associatedAddressablePoint ""
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bridgedReceiverOffset ""
set_interface_property s0 bridgesToReceiver ""
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 irq_to_hps irq Output 1


# 
# connection point event_ready
# 
add_interface event_ready conduit end
set_interface_property event_ready associatedClock clock
set_interface_property event_ready associatedReset ""
set_interface_property event_ready ENABLED true
set_interface_property event_ready EXPORT_OF ""
set_interface_property event_ready PORT_NAME_MAP ""
set_interface_property event_ready CMSIS_SVD_VARIABLES ""
set_interface_property event_ready SVD_ADDRESS_GROUP ""

add_interface_port event_ready event_ready event_ready Input 1
add_interface_port event_ready clear_irq_from_hps clear_irq Input 1


set_module_assignment embeddedsw.dts.vendor "Dar"
set_module_assignment embeddedsw.dts.compatible "dev,irq_controller"
set_module_assignment embeddedsw.dts.group "fpgaperiph"